# Generated by Django 3.1.6 on 2021-02-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='users_profile_pic/default_profile_pic.jpg', upload_to='users_profile_pic/'),
        ),
    ]
