# Generated by Django 3.1.6 on 2021-02-12 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generics', '0006_category'),
        ('review', '0003_auto_20210207_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generics.category'),
            preserve_default=False,
        ),
    ]
